### ISSUE TITLE
ported oncel_cell 

### ISSUE THREAD

**Issue by zaxguo** [dingelish/sgx-world#3]
Hi Yu, 
I have ported once_cell crates in https://github.com/zaxguo/once_cell.git (master, see the latest one commit). Please consider incorporating it here. Thanks!

**Comment by dingelish** [comment]
thanks @zaxguo ! i'll maintain a fork based on your fork (within 2days) and make sure it'll be compatible with future teaclave sgx sdk. thanks!

**Comment by dingelish** [comment]
please refer to 774e462c8b532d0f0dc662bd81c07a440806c13a

**Comment by zaxguo** [comment]
> thanks @zaxguo ! i'll maintain a fork based on your fork (within 2days) and make sure it'll be compatible with future teaclave sgx sdk. thanks!

Awesome! My pleasure.
