### ISSUE TITLE
can not disable perf-cache feature in regex-sgx

### ISSUE THREAD

**Issue by cipepser** [dingelish/sgx-world#6]
Hi, I would like to stop using `thread_local`, so tried to disable `perf-cache` feature in regex-sgx. However,  I got following compile error.

```
   Compiling regex v1.3.1 (https://github.com/mesalock-linux/regex-sgx#95cad522)
error[E0432]: unresolved import `std::sync::Mutex`
  --> /root/.cargo/git/checkouts/regex-sgx-dc3d971bffeb8599/95cad52/src/cache.rs:44:9
   |
44 |     use std::sync::Mutex;
   |         ^^^^^^^^^^^-----
   |         |          |
   |         |          help: a similar name exists in the module: `mutex`
   |         no `Mutex` in `sync`

error[E0412]: cannot find type `Vec` in this scope
  --> /root/.cargo/git/checkouts/regex-sgx-dc3d971bffeb8599/95cad52/src/cache.rs:48:22
   |
48 |         stack: Mutex<Vec<T>>,
   |                      ^^^ not found in this scope
   |
help: consider importing this struct
   |
42 |     use std::prelude::v1::Vec;
   |

error[E0412]: cannot find type `Box` in this scope
  --> /root/.cargo/git/checkouts/regex-sgx-dc3d971bffeb8599/95cad52/src/cache.rs:59:31
   |
59 |         _phantom: PhantomData<Box<dyn Send + Sync + UnwindSafe>>,
   |                               ^^^ not found in this scope
   |
help: consider importing this struct
   |
42 |     use std::boxed::Box;
   |
```

I've patched like [this](https://github.com/cipepser/regex-sgx/commit/10d695aaa0210f4dc61cb6d893019b19d33ef98f), and checked passing the compilation in my environment. Can I send a pull request?

**Comment by dingelish** [comment]
thanks bro! i simply take your patch :-) along with another little fix

https://github.com/mesalock-linux/regex-sgx/commit/76aef86f9836532d17764523d0fa23bb7d2e31cf

please check if this works! thanks!

**Comment by cipepser** [comment]
Thank you! It works well. But I have another topic about this issue. To tell the truth, I want to use `regex-sgx` through `pem-rs-sgx` crate. But `pem-rs-sgx` don't have a feature to disable `perf-cache` in `regex-sgx`. Could you add a such feature to `pem-rs-sgx` ? I want to import `pem-rs-sgx` in `Cargo.toml` like this:

```Cargo.toml
[dependencies]
regex = { git = "https://github.com/mesalock-linux/regex-sgx", default-features = false, features = ["std", "unicode", "mesalock_sgx", "perf-dfa", "perf-inline", "perf-literal"] }
```

**Comment by cipepser** [comment]
If you don't have enough time to implement it, I will sent a pull request. Please feel free to tell me.

**Comment by dingelish** [comment]
@cipepser please checkout https://github.com/mesalock-linux/pem-rs-sgx/commit/fdfef4f24a9fb3fa72e8a71bb28bd8ff15feff2f

:-)

**Comment by cipepser** [comment]
Everything works well!! Thank you for your quick job!

**Comment by cipepser** [comment]
I close this issue, thank you.
